name: build Android APK
on: push
  # push:
  #   branches-ignore: 
  #     - "release"
    
jobs: 
  Build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message,'[apk]') || contains(github.event.head_commit.message,'[build apk]')}}

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
        
      - name: Set environment variable
        run: echo "BASIC_HEADER_HASH=${{ secrets.BASIC_HEADER_HASH }}" >> $GITHUB_ENV

      # - name: Replace occurrences
      #   run: |
      #     for file in $(find . -type f -name '*.js' -o -name '*.tsx' -o -name '*.ts'); do
      #       sed -i "s|\${process.env.BASIC_HEADER_HASH}|${BASIC_HEADER_HASH}|g" "$file"
      #     done

      # - name: cat file
      #   run: cat ./Utilities/apiAuthorization.js

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install
        
      - name: CD into frontend folder
        run: cd ./frontend
        
      - name: 🚀 Build app
        run: eas build -p android --profile preview --local --non-interactive --clear-cache --output "./apk/android-preview-build.apk"
        
          

# Upload the file generated
      - uses: actions/upload-artifact@v4
        with:
          name: buildArtifact
          path: ./apk/android-preview-build.apk
