
name: Check Branch Naming

on:
  create:
    branches:
      - '*'

jobs:
  check-branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          branch_name=$(echo "${GITHUB_REF##*/}")
          if [[ "$branch_name" != feature_* ]]; then
            echo "Branch name does not start with feature_: $branch_name"
            exit 1
          fi
