name: iOS App Release Build

on: push
  # Specify when you want the build to run here

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message,'[expo ios]') }}
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Set environment variable
        run: echo "BASIC_HEADER_HASH=${{ secrets.BASIC_HEADER_HASH }}" >> $GITHUB_ENV
      
      - name: Replace BASIC_HEADER_HASH
        run: |
          find . -type f \( -name '*.js' -o -name '*.tsx' -o -name '*.ts' \) | while read -r file; do
            sed -i '' "s|\${process.env.BASIC_HEADER_HASH}|${BASIC_HEADER_HASH}|g" "$file"
          done
        env:
          BASIC_HEADER_HASH: ${{ secrets.BASIC_HEADER_HASH }}
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Install CocoaPods
        run: sudo gem install cocoapods


      - name: Check installed Xcode versions
        run: |
          ls -l /Applications | grep Xcode
          
      - name: Build iOS app
        run: eas build --platform ios --local --profile production --non-interactive --output ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.ipa
