name: iOS App Release Build

on: push
  # Specify when you want the build to run here

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message,'[expo ios]') }}
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build iOS app
        run: eas build --platform ios --local --non-interactive --output ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.ipa
